### PR TITLE
fix: Select option background for dark theme

### PR DESCRIPTION
**Pull request by Lanseria**
## Description of Problem

The selection dropdown box is incorrect in the dark theme

## Proposed Solution

should black background

### CODE REVIEW

**Comment by yyx990803** [comment]
Can you post a before / after screenshot? I don't see where the current color is "incorrect".

**Comment by Lanseria** [comment]
> Can you post a before / after screenshot? I don't see where the current color is "incorrect".

before

image

after

image

**Comment by skirtles-code** [comment]
This change seems to impact some other elements too, such as the `<textarea>` example.

**Comment by skirtles-code** [comment]
I've attempted something similar in #1587, but without the impact on other elements.

**Pull request closed without merging**
