### PR TITLE
Fix for #1691

### PR DESCRIPTION
**Pull request by BilleLind**
## Description of Problem

404 errors on the links in /tutorials/#step-15 
- Quick Start
- Main Guide
- Examples

## Proposed Solution

Changing the links from markdown based links `[]() to <a href="">` like in the previous steps

## Additional Information
Tough unrelated, it is my first time committing to an open source.

### CODE REVIEW

**Comment by BilleLind** [comment]
I would wager it is due to createMarkdownRenderer from  vitepress, since i dont understand most of the code, i think it is because of a missing base string =>

in https://github.com/vuejs/docs/blob/main/src/tutorial/tutorial.data.ts
it utilizes "createMarkdownRenderer" from vitepress,

which accepts 3 params: srcDir, options and **base**
https://github.com/vuejs/vitepress/blob/main/src/node/markdown/markdown.ts

**Comment by BilleLind** [comment]
By changing the const md in /tutorial/tutorial.data.ts (added , '/' )

`const md = createMarkdownRenderer(process.cwd(), {
      // @ts-ignore
      highlight: await createHighlighter()
    }, '/')
`
it makes it possible to utilize [example](/examples/), though with a flash of 404 before going to the correct page, which I am uncertain if it is caused by it being run locally. 

Should I commit it along with the current pull request?

**Comment by yyx990803** [comment]
I think simply adding the missing base to `createMarkdownRenderer` is good enough. I'm not seeing flash of 404 when testing locally.

**Comment by BilleLind** [comment]
Deployed the fix for createMarkdownRenderer and the links are working, also reverted the prior changes made in step 15

**Pull request merged**
