### PR TITLE
add vue 2 nes banner

### PR DESCRIPTION
**Pull request by leonibr**
## Description of Problem
Add the approved banner of Vue 2 NES 

## Proposed Solution
Replaced the existent Banner component code to accommodate the changes

## Additional Information

⚠️ I removed the code from active banner which is injected from  vue school website

### CODE REVIEW

**Comment by bencodezen** [comment]
Thanks for the PR @leonibr! I'm not sure where the approval from this is coming from, so I've requested Evan as the reviewer for this, but if you can provide additional context (you can reach via Discord or Twitter if it helps), I can try to help expedite this!

**Comment by leonibr** [comment]
Great, @bencodezen, I am from Herodevs,  a Vue partner company that provides Vue 2 Never-ending-support, I believe Evan is the right one to review this since he was the one providing instructions to our marketing team of where and how to do it.

**Comment by jwcalles** [comment]
@bencodezen hey there! I am on the HeroDevs team as well and have been working with @yyx990803 on this project. I wanted to echo your thoughts about having Evan as the reviewer, I think that is great as we can keep the conversation going.  @leonibr thank you for getting this ready for review!

**Comment by yyx990803** [comment]
I've removed the config change. Vue School banner injection has already been toggled off from their side.

**Comment by jwcalles** [comment]
Thank you Evan! Excited to see it on the site!

**Pull request merged**
