### PR TITLE
Vueschool links fundamentals

### PR DESCRIPTION
**Pull request by danielkellyio**
This PR adds Vue School links to the documentation to supplement the documentation with free training videos. The intent of this PR is to provide links to all lessons considered complete and ready for linking as discussed in [PR#964](https://github.com/vuejs/docs-next/pull/964).

This will provide more time to work on the Class Bindings video in order to make it most unified and useful with the Vue 3 docs. 

Thanks!

### CODE REVIEW

**Review by skirtles-code — CHANGES_REQUESTED** [review]
Could you add a blank line after each `<VideoLesson>` so it doesn't run into the content that follows it?

I just did a quick check of a few of the videos and it looks like there aren't any subtitles on them. Is that something that's being actively worked on?

Thanks.

**Comment by danielkellyio** [comment]
@skirtles-code whoops, yes! Line breaks added after each video link. 

The timeline for the subtitles is end of next week. 

Thanks!

**Comment by danielkellyio** [comment]
@skirtles-code the subtitles have been added to all the videos in this PR. Thanks!

**Review by skirtles-code — CHANGES_REQUESTED** [review]
We've merged #964 so that the community can start benefiting from these videos. I'm going to keep this PR open for now so that we have somewhere to continue discussing the videos.

I've gone through the subtitles and made some notes below.

The video `computed-properties-in-vue-3` doesn't seem to have subtitles at present.

In the lists below...

* **Typo** refers to something that appears to be a mistake in the subtitles.
* **Case** refers to something that appears to be in the wrong case (upper case, lower case, etc.) but is otherwise correct.
* **Mismatch** refers to places where the subtitles don't match the narration but still make sense. This could be intentional but in the cases I've listed below I couldn't see any obvious reason why we would want them to differ.

---

`conditional-rendering-in-vue-3`

* **Case**, 0:05, `html ➔ HTML`.
* **Case**, 1:25, 1:35, 3:03. The text `addItem` is written in camelCase but it isn't clear why as it doesn't seem to be referring to an identifier in the code. Contrast that with 3:30, which uses `Add Item button`. That makes sense to me as `Add Item` is the label in the code.
* **Mismatch**, 4:18, `our v-on ➔ the v-on`.

---

`methods-in-vue-3`

* **Typo**, 0:15, `objects top level ➔ object's top-level`.
* **Typo**, 0:25, `it's data ➔ its data`.
* **Typo**, 1:00, `Conviniently ➔ Conveniently`.
* **Typo**, 4:15, `different that ➔ different than`.

---

`user-events-in-vue-3`

* **Case**, 0:05, 0:20, `Javascript ➔ JavaScript`.
* **Mismatch**, 2:00, `add the v-on:click ➔ add v-on:click`.
* **Mismatch**, 2:45, `then our ➔ that our`.
* **Mismatch**, 2:55, `to click events ➔ to the click event`.
* **Mismatch**, 3:00, `to other ➔ for other`.
* **Case**, 3:25, `vue's ➔ Vue's`.
* **Typo**, 3:30, `keyboard based ➔ keyboard-based`.
* **Mismatch**, 3:50, `the .enter ➔ .enter`.
* **Mismatch**, 4:00, `we can ➔ we'll`.
* **Typo**, 4:30, `let's ➔ lets`.
* **Typo**, 4:55, `short-hand ➔ shorthand`.
* **Typo**, 5:22, `although ➔ a little`.
* **Mismatch**, 5:25, `it's ➔ is`.
* **Mismatch**, 5:39, `into ➔ to`.

---

`user-inputs-vue-devtools-in-vue-3`

* **Mismatch**, 0:55, `shopping ➔ shopping list`.
* **Mismatch**, 1:40, `of newItem ➔ of the newItem`.
* **Mismatch**, 2:35, `look ➔ take a look`.
* **Mismatch**, 4:02, `and then create ➔ then we'll create`.
* **Typo**, 4:20, `v-modal ➔ v-model`.
* **Typo**, 5:05, `to select in ➔ is selected`.
* 6:20, no subtitles for that sentence.
* **Typo**, 7:25, `Since check ➔ Since checked`.
* **Mismatch**, 7:55, `a checkbox ➔ our checkbox`.
* **Typo**, 8:03, `it's value ➔ its value`.
* **Case**, 8:45, `icecreamFlavors ➔ iceCreamFlavors`.

---

`using-vue-dev-tools-with-vuejs-3`

* **Case**, 0:50, `chrome ➔ Chrome`.
* **Case**, 0:52, `vue.js ➔ Vue.js`.
* **Typo**, 1:00, `shoping ➔ shopping`.
* **Mismatch**, 1:05, `that we have Vue ➔ that Vue is`.
* **Mismatch**, 1:35, `know ➔ note`. Maybe I'm mishearing it but `note` makes more sense to me.

---

`list-rendering-in-vue-3`

* **Mismatch**, 0:35, `then use ➔ then we can use`.
* **Typo**, 0:40, `it's own ➔ its own`.
* **Typo**, 1:50, `our item ➔ our items`.
* **Case**, 2:50, `vue ➔ Vue`.
* **Typo**, 2:55, `to index ➔ the index`.
* **Mismatch**, 3:15, `for ➔ with`.
* **Typo**, 3:25, `works great ➔ work great`.
* **Typo**, 3:30, `our items format ➔ the format`.
* **Typo**, 4:30, `items labels ➔ item's label`.
* **Typo**, 4:50, `let's just change key ➔ let's change`.
* **Mismatch**, 6:15, `rendering ➔ rendered`.

**Comment by danielkellyio** [comment]
@skirtles-code the subtitle issues mentioned above have been corrected. Thanks!

**Comment by skirtles-code** [comment]
@danielkellyio Great, thanks!

As far as I'm aware there's nothing more that needs to be done here so I'm going to close this PR.

**Pull request closed without merging**
