### PR TITLE
Add translation link to ru.vuejs.org

### PR DESCRIPTION
**Pull request by Ibochkarev**
## Description of Problem

Hello @yyx990803 and @bencodezen, i am a member of the organization [translation-gang](https://github.com/translation-gang/docs-ru).

We have finished translating the documentation into Russian and would like to place a link to the official website of the documentation with the translation, as well as link the domain https://ru.vuejs.org/ for https://vuejs-doc-ru.vercel.app/.

You can help with the domain and consider this PR?

PS: Added additional information here https://github.com/vuejs/docs/issues/478#issuecomment-1943122897

Repository: https://github.com/vuejs-translations/docs-ru

Discussion: https://github.com/orgs/vuejs-translations/discussions/12#discussioncomment-8756236

### CODE REVIEW

**Comment by NataliaTepluhina** [comment]
@Ibochkarev I've forwarded the link request to Evan and will merge as soon as domain is linked.

**Comment by Ibochkarev** [comment]
@Jinjiang The repository has been moved https://github.com/vuejs-translations/docs-ru

Discussion https://github.com/orgs/vuejs-translations/discussions/12#discussioncomment-8756236

**Comment by Ibochkarev** [comment]
> @Ibochkarev would it be fine to transfer the translation to `vuejs-translations` organisation (please see step 4 here: https://github.com/vuejs-translations/guidelines?tab=readme-ov-file#high-level-steps-of-working-on-a-new-translation). This way we could handle the deployments from our end.

Done

**Comment by Jinjiang** [comment]
Please also update this page https://github.com/vuejs/docs/blob/main/src/translations/index.md
The domain is under deploying. Then after all this PR is able to be merged. Thanks.

**Comment by yyx990803** [comment]
DNS updated - may require some time for SSL certs to be generated. Congrats and thanks to everyone who contributed!

**Pull request merged**
