### PR TITLE
Add Airbrake integration to errorHandler docs

### PR DESCRIPTION
**Pull request by kyrylo**
I work for Airbrake. While working on a Vue app I stumbled upon the docs that
mention error handling with 3rd party services (Sentry, Bugsnag). I also saw a
PR adding Bugsnag: https://github.com/vuejs/vuejs.org/pull/1311

I thought, it would be nice to mention Airbrake as well, since we have also have
a decent support for Vue.

### CODE REVIEW

**Comment by skirtles-code** [comment]
The equivalent PR for the Vue 2 docs: https://github.com/vuejs/vuejs.org/pull/2881

**Comment by skirtles-code** [comment]
Hi @kyrylo. Thanks for the PR.

We're generally quite cautious about mentioning third-party tools in the documentation, as it can be viewed as an endorsement or recommendation. We typically only list tools that the Vue core team have used and had good experiences with.

I reached out to the core team to see whether anyone was familiar with Airbrake but none of them have used it. I'm afraid we won't be able to include Airbrake in the documentation at this stage, but if it gains traction within the Vue community then it should be possible to include it at some point in the future.

**Comment by destari** [comment]
So on. this page:
https://v3.vuejs.org/api/application-config.html#errorhandler
where you mention "official integrations", that isn't actually the case?   Seems very unfortunate for the Due community if the only "official integrations" are the ones that the developers themselves have used.  Seems opposite of open/inclusive.

**Comment by destari** [comment]
Makes sense, thanks for the detail and extra clarification!

**Pull request closed without merging**
