### PR TITLE
fix: double dashes in command with vite

### PR DESCRIPTION
**Pull request by JensVanhulst**
## Description of Problem

Double dashes in the scaffolding command with vite
```sh 
npm init vite <proj-name> -- --template vue
```

## Proposed Solution
```sh 
npm init vite <proj-name> --template vue
```

### CODE REVIEW

**Review by sodatea — CHANGES_REQUESTED** [review]
Need to differentiate npm 6 and npm 7. See https://vitejs.dev/guide/#scaffolding-your-first-vite-project

**Comment by JensVanhulst** [comment]
@sodatea 
Well it is not documented on the vue 3 docs as you can see below. 
Isn't this confusing ?
image

**Comment by sodatea** [comment]
So I'm not closing this PR but requesting you to document both npm 6 & npm 7 behavior.
Otherwise it will confuse npm 7 users.

**Comment by JensVanhulst** [comment]
Should be fixed now.

**Review by sodatea — APPROVED** [review]

**Pull request merged**
