### PR TITLE
fix: og preview

### PR DESCRIPTION
**Pull request by himself65**
https://www.opengraph.xyz/url/https%3A%2F%2Fdeploy-preview-2633--vuejs.netlify.app%2F

Fixes: #2631

### CODE REVIEW

**Comment by brc-dd** [comment]
Logo as an og:image is not a good idea. It will be stretched/cropped most likely while sharing. 1200 x 630 px image is usually recommended.

**Comment by himself65** [comment]
> Logo as an og:image is not a good idea. It will be stretched/cropped most likely while sharing. 1200 x 630 px image is usually recommended.

I just found that vue2 are using the same image, is there any better image to use?

https://www.opengraph.xyz/url/https%3A%2F%2Fv2.vuejs.org%2F

**Comment by brc-dd** [comment]
Yeah but in the previews you see how that thing is looking weird.

**Comment by brc-dd** [comment]
Facebook:

image

LikedIn:

image

Twitter:

image

Discord:

image

WhatsApp:

image

**Review by brc-dd — APPROVED** [review]
Adjusted things a bit. This looks fine for most of the stuff except LinkedIn (and certain padding issues if one looks closely). I'll ask Kia to design some cool image for this and we can replace that later.

**Pull request merged**
