### PR TITLE
Shuffle team members

### PR DESCRIPTION
**Pull request by Jinjiang**
## Description of Problem

Shuffle team members like the v2 doc site.

## Proposed Solution

Provide a `shuffleMembers()` function to process the data ahead.

## Additional Information

It's on the TODO list of `@vue/theme`. However, now I feel it's better done here. Thanks.
https://github.com/vuejs/theme/issues/36

### CODE REVIEW

**Comment by xfq** [comment]
The avatar doesn't seem to match the person?

See the screenshot below:

avatar

**Review by NataliaTepluhina — APPROVED** [review]
Thank you for adding the shuffling, @Jinjiang!

**Comment by tony19** [comment]
@NataliaTepluhina Did you notice [the bug](https://github.com/vuejs/docs/pull/1880#issuecomment-1204698307) mentioned above? If you refresh the page, the avatars no longer match their profiles.

**Comment by Jinjiang** [comment]
let me take a look

**Comment by KiritaniAyaka** [comment]
Perhaps the param of shuffle function caused it

**Comment by KiritaniAyaka** [comment]
There is another bug.

I can't reproduce them on my local machine.
It looks like they both only appear in the development environment. so weird...

image

**Comment by Jinjiang** [comment]
Caused by the SSG process. Fixed in #1880

**Pull request merged**
