### PR TITLE
Improve spelling

### PR DESCRIPTION
**Pull request by sanmai-NL**
If you have any questions, please ask.

### CODE REVIEW

**Comment by bencodezen** [comment]
I'm not sure the "collocation" spelling is as much of an issue. Seems to be spelled correctly:

https://www.merriam-webster.com/dictionary/collocate

@skirtles-code What do you think?

**Comment by sanmai-NL** [comment]
> I'm not sure the "collocation" spelling is as much of an issue. Seems to be spelled correctly:
> 
> https://www.merriam-webster.com/dictionary/collocate
> 
> @skirtles-code What do you think?

Collocate has a different meaning that colocate, the latter is meant.

**Comment by sanmai-NL** [comment]
@skirtles-code I noticed that this PR is listed by GitHub as 'Changes requested'. What is the next step?

**Review by skirtles-code — APPROVED** [review]
I spent a bit of time researching the difference between 'collocate' and 'colocate'. It isn't clear to me whether we really do mean 'colocate' or 'collocate'. Both seem plausible to me.

My eventual reasoning, possibly dubious, is that I was pronouncing the word in the docs as 'coh-loh-cate' in my mind, which is not how 'collocate' is pronounced.

**Pull request merged**
