### PR TITLE
Fix `watch` examples

### PR DESCRIPTION
**Pull request by jay-es**
## Description of Problem
The example code for `watch` may cause race conditions.
~~However, adding cleanup process makes the code complex and difficult to understand.
So I added a note.~~
↓
Disable the input field until the request is resolved.

### CODE REVIEW

**Comment by NataliaTepluhina** [comment]
@jay-es maybe we could disable the input field until the request is resolved? This way we would be able to skip the cleanup process and also wouldn't require the `info` badge?

**Comment by jay-es** [comment]
@NataliaTepluhina Thank you for your advice. I will try it!

**Comment by jay-es** [comment]
@NataliaTepluhina I fixed. Could you please review it again when you have a moment?:pray:

**Comment by NataliaTepluhina** [comment]
@jay-es thank you for adding the disabled state! I've updated your code a little to use the reactive property for `disabled` state instead of direct DOM manipulation through a ref. Also, let's not care about focusing a field here since at this point we haven't explained template refs to users yet. Could you please check the changes and let me know if you're okay with them? If yes, I'll proceed to merge

**Comment by jay-es** [comment]
@NataliaTepluhina Much smarter code!
Thank you for fixing and please merge.

**Pull request merged**
