### PR TITLE
imported and changed twitter icon to new logo

### PR DESCRIPTION
**Pull request by stevenks17**

### CODE REVIEW

**Comment by NataliaTepluhina** [comment]
@stevenks17 it looks like `@vue/theme` doesn't have a `VTIconX` export 🤔  Maybe we'd need to update the theme first

**Comment by stevenks17** [comment]
@NataliaTepluhina  I recently did this for theme and I believe it was merged in https://github.com/vuejs/theme/pull/101#event-10797221271 so I think Theme just has to redeploy the new main branch if I am understanding it correctly?

**Comment by NataliaTepluhina** [comment]
@stevenks17 I've updated `@vue/theme` to v2.2.5 for docs, could you please rebase onto latest `main` branch? hopefully, this will fix the  failing deploy job 🙏🏻

**Comment by stevenks17** [comment]
@NataliaTepluhina I believe I am all green now!

**Comment by NataliaTepluhina** [comment]
@stevenks17 indeed! Let's get this PR merged while all the pipelines are passing 😅

**Pull request merged**
